### ISSUE TITLE
Feature request: Function to add confidence bands

### ISSUE THREAD

**Issue by tobiasmuetze** [pharmaverse/ggsurvfit#147]
The function `add_confidence_interval()` add pointwise confidence intervals to the Kaplan-Meier curve. In same settings confidence bands (and not pointwise confidence intervals) are of interest. 

It would be great to add a function `add_confidence_bands()` to the package. To the best of my knowledge, confidence bands are not calculated by the `survival` package. However, the R package [km.ci](https://cran.r-project.org/package=km.ci) provides confidence bands.

**Comment by ddsjoberg** [comment]
Can you please provide more details about the CI methods you're interested in?

**Comment by ddsjoberg** [comment]
Hi @tobiasmuetze , please feel free to re-open this issue when you have time to provide code and data examples. thanks
