### ISSUE TITLE
Justification of text in risktables

### ISSUE THREAD

**Issue by ddsjoberg** [pharmaverse/ggsurvfit#165]
I think at the moment, the text in the risktable is centered and sometimes the first number is truncated a bit. Is there a better default?

<img width="687" alt="image" src="https://github.com/pharmaverse/ggsurvfit/assets/26774684/a2083fa7-eabd-4242-9f42-4987fc9abfa3">

**Comment by psoldath** [comment]
And the problem gets worse when the plot is set to not expand (coord_cartesian(expand = FALSE)).

I think a better default would be better if the risk table y-axis text (and probably also the risk table headings) was right-aligned and with a small right margin from the point of x = 0 like in the following plot. This would create more white space left of the plot, but it would get rid of the problem with truncated text especially when the plot is set to not expand. 

<img width="467" alt="Skærmbillede 2023-09-10 kl  02 58 55" src="https://github.com/pharmaverse/ggsurvfit/assets/146545458/86bf712b-e0b2-4258-ab69-604db65db2bb">

**Comment by ddsjoberg** [comment]
@psoldath thanks for the suggestion. can you provide a code example?

**Comment by psoldath** [comment]
@ddsjoberg No I'm sorry, I'm a real novice to R and I don't know how to code it. I guess the risktable titles should be left-aligned set to the "plot" position, while the y-axis texts should be right-aligned, and then, if the y-axis texts are too long, a relative margin should be added to the left of the y-axis title of the plot to keep the risk table numbers aligned with the x-axis ticks of the plot without truncating the numbers?

**Comment by ddsjoberg** [comment]
To keep it simple, i'll probably just increase the default padding on the x=0 side.
