### ISSUE TITLE
Feature request: Expand ggsurvfit to include cox regression objects to plot adjusted survival curves

### ISSUE THREAD

**Issue by Yunuuuu** [pharmaverse/ggsurvfit#186]
This request was made in https://github.com/pharmaverse/ggsurvfit/issues/140, but the content leads us to a currently missing issue at https://github.com/ddsjoberg/ggsurvfit/issues/9. Following is the implement of `survminer` while it cannot add a risk table.
``` r
library(survival)
library(survminer)
#> Loading required package: ggplot2
#> Loading required package: ggpubr
#>
#> Attaching package: 'survminer'
#> The following object is masked from 'package:survival':
#>
#>     myeloma
fit <- coxph(Surv(stop, event) ~ size + strata(rx), data = bladder)
ggadjustedcurves(fit, data = bladder, variable = "rx")
```
![image](https://github.com/pharmaverse/ggsurvfit/assets/19575010/ea30e17f-2420-4663-9da1-e008cf9752f2)
<sup>Created on 2023-12-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by Yunuuuu** [comment]
Sorry, I missed the feature described in https://www.danieldsjoberg.com/ggsurvfit/articles/gallery.html. It would be beneficial to add more detailed descriptions to the help documents at https://www.danieldsjoberg.com/ggsurvfit/reference/survfit2.html.

For me, it would be okay to close the issue.

**Comment by ddsjoberg** [comment]
Thanks for the posts
