### ISSUE TITLE
Feature request: Add type = "cloglog" (log minus log survival)

### ISSUE THREAD

**Issue by avishaitsur** [pharmaverse/ggsurvfit#194]
**The problem:** Log minus log survival curves are widely used to assess the assumption of proportionality of hazards. While plotting these curves is available using the `survival` and `survminer` packages, it is currently unavailable in `ggsurvfit`.

**Proposed solution:** Add an option of `type = "cloglog"` to `ggsurvfit::tidy_survfit`.
Specifically, this would need to be added in the:
- Function call
```
tidy_survfit <- function(x,
                         times = NULL,
                         type = c("survival", "risk", "cumhaz", "cloglog"))
```
- Select transformation function
```
  if (rlang::is_string(type)) {
    .transfun <-
      switch(type,
             survival = function(y) y,
             cuminc = function(y) y,
             risk = function(y) 1 - y,
             # survfit object contains an estimate for Cumhaz and SE based on Nelson-Aalen with or without correction for ties
             # However, no CI is calculated automatically. For plotting, the MLE estimator is used for convenience.
             cumhaz = function(y) -log(y),
             cloglog = function(y) log(-log(y))
      )
  } else {
    .transfun <- type
  }
  if (!rlang::is_function(.transfun)) {
    cli_abort("The {.var type} argument must be one of {.val {c('survival', 'risk', 'cumhaz', 'cloglog')}}, or a function.")
  }
```
- Add estimate type label:
```
      estimate_type_label =
        dplyr::case_when(
          rlang::is_string(.env$type) && .env$type %in% "survival" ~ "Survival Probability",
          rlang::is_string(.env$type) && .env$type %in% "cuminc" ~ "Cumulative Incidence",
          rlang::is_string(.env$type) && .env$type %in% "risk" ~ "Risk",
          rlang::is_string(.env$type) && .env$type %in% "cumhaz" ~ "Cumulative Hazard",
          rlang::is_string(.env$type) && .env$type %in% "cloglog" ~ "Log Minus Log Survival",
          TRUE ~ rlang::expr_deparse(.transfun)
        )
```
- Monotonicity
```
    x$monotonicity_type <-
      switch(type,
             "survival" = "decreasing",
             "cuminc" = "increasing",
             "risk" = "increasing",
             "cumhaz" = "increasing",
             "cloglog" = "increasing"
      )
```
- Initial survival estimates of value one should be ignored as `log(-log(1))` reaches infinity.
- Unlike the other figures, the x-axis is commonly on the log scale.

**Example of a figure using the `survival` package**
![cloglog_plot](https://github.com/pharmaverse/ggsurvfit/assets/50148164/3d85dcb8-a40c-4d90-8e4d-6d00bb6c07d7)

**Example of the desired figure using the `ggsurvfit` package**
![cloglog](https://github.com/pharmaverse/ggsurvfit/assets/50148164/c9e24c77-2147-459b-b2f1-1311f5ec5590)

**Comment by ddsjoberg** [comment]
Dear @avishaitsur , 

i think that is a great request. I see you've done the research into he package's internals. Would you like to submit a PR to add this?
