### ISSUE TITLE
At risk numbers from start of Interval

### ISSUE THREAD

**Issue by chprogr** [pharmaverse/ggsurvfit#198]
**Is your feature request related to a problem? Please describe.**
when i get the atrsik numbers from ggsurvfit package i see that the numbers reported are from end of interval. is there a way to get from start of interval.
For ex:  day 0, day 30(1-30), day 180(31 to 180 ),day 365(181 to 365) . 

**Describe the solution you'd like**
I would like to see the atrisk numbers from start of intervals like o, day 1,day 31,day 181 for the intervals described above.

**Comment by ddsjoberg** [comment]
Thanks for your post.

That sounds like `"n.censor"`, which is already available. If that is not what you're looking for, can you please update your post the a reproducible example (code and data I can run on my machine) illustrating your request. 
https://www.danieldsjoberg.com/ggsurvfit/reference/add_risktable.html

**Comment by chprogr** [comment]
not the censored subjects in the interval.  I am looking for n.risk numbers from begining of interval. I a attaching the template.
[Interval Post Procedure Days.docx](https://github.com/pharmaverse/ggsurvfit/files/14964563/Interval.Post.Procedure.Days.docx)

**Comment by ddsjoberg** [comment]
Dear @chprogr , 

- You're looking to create a table (not a figure)? This package exists for illustrating time to event outcomes.
- If you're asking how to calculate the value you're after, please feel free to re-open this issue after you've posted an example that includes data. You can use `dput()` or `tibble::tribble()` to construct an example data set. You can also use the  `df_lung` that is exported with this package. reprex.tidyverse.com is also a great resource for constructing reproducible examples.

Hope that helps.

**Comment by chprogr** [comment]
![image](https://github.com/pharmaverse/ggsurvfit/assets/159571535/0d994ea0-532b-45f1-9df2-1946492ac1c6)

i just provided the table as an example I have attached sas output with annotation.

**Comment by ddsjoberg** [comment]
Thank you for the additional context. I saw the document and SAS code. If you needed assistance calculating the quantity you're after, I could help you if you provided example raw data.

But it looks like you're seeking to put these numbers on a ggsurvfit figure: that is unfortunately not supported.

**Comment by chprogr** [comment]
sure. Thank you Daniel.

**Comment by ddsjoberg** [comment]
anytime, happy programming!
