### ISSUE TITLE
Feature request: Plotting for survme objects

### ISSUE THREAD

**Issue by FBartos** [pharmaverse/ggsurvfit#225]
**Is your feature request related to a problem? Please describe.**

Hi, I really like the visualizations produced by the package, and I'm currently incorporating the figures into JASP. The plotting works very well with the coxph function, but the fraily support is limited and superseded by survme according to the documentation. It would be great if the ggsurvfit function was compatible with the coxme models as well. Any idea whether it's somewhere on the roadmap?

Cheers,
Frantisek

**Comment by ddsjoberg** [comment]
It is not on the roadmap for now. Can you mock up something that looks like what you'd like to see? (Please also include code for calculating any quantities that appear in the mock-up.)

**Comment by FBartos** [comment]
Not really expert enough on CoxPH to make this happen. Thanks for the quick answer!

**Comment by ddsjoberg** [comment]
OK, the mock up doesn't need to be created programmatically. I just need an idea of what you're looking to get in the end. I'll go ahead and close the issue for now. But feel free to re-open if you mock up what the result would look like.
